[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "joblib>=1.5.3",
    "numpy>=2.4.6",
    "onnx>=1.21.0",
    "onnxconverter-common>=1.16.0",
    "onnxmltools>=1.16.0",
    "scikit-learn>=1.8.0",
    "xgboost>=3.2.0",
]
